### ISSUE TITLE
A problem about converting necCDF to CSV files

### ISSUE THREAD

**Issue by Zhu3520** [sagarlimbu0/OCO2-OCO3#37]
Hello, thank you for your method and code for '**Convert_netCDF_to_CSV_files**'. My operating system is Win10 and I have a problem when I try to convert nc4 files to csv files. Everything is normal before the last step. After defining the convert function named '**convHdf**', I used this function to my own files, but my computer gave an error:  **PermissionError: [Errno 13] Permission denied: b'F:/test'**. I used some methods, but still haven't eliminated the problem. Do you know how to solve this problem？Thank you.

**Comment by sagarlimbu0** [comment]
Apologies for late response. I believe this issue has to do with permission issue with file access. You can check if the path specified are in correct path or provide screenshot of the error generated.
