### ISSUE TITLE
OCO2-OCO3 API Endpoints and Documentation

### ISSUE THREAD

**Issue by Mitchell-Odili** [sagarlimbu0/OCO2-OCO3#38]
Hello, 

I'm looking for OCO2-OCO3 API Endpoints and Documentation. 

Could you point me in the right direction?

**Comment by sagarlimbu0** [comment]
Apologies for late response. These are the API endpoints with documentation for retrieving the data that are available in Earthdata web. 
[Earthdata API](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/api#edsc)

However, I could not find any concrete examples on retrieving data through API, but I have generated a code using `pydap` library to retrieve desired file through openDap. here, in this example:
[pydap](https://github.com/sagarlimbu0/ARSET_2022_spring/blob/main/Different_sections/vol_2_pydap_earthdata_login.ipynb)

Let me know if you have further questions.

**Comment by Mitchell-Odili** [comment]
Thanks. This is fine. Appreciated
